name: Unit Tests

on:
  push:
    branches:
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Ruby using Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
          bundler-cache: true
          bundler: "2.5.23"

      - name: install gems
        run: bundle install

      - name: test
        run: bundle exec rake test
